name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List directory content
        run: ls -la

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
           mkdir test 
           cd test 
           ssh-keyscan github.com >> ~/.ssh/known_hosts
           git clone git@github.com:ennooc/blog-web.git 
